"""
Layer 2: Autonomous Planning Agent
====================================
Uses LangGraph to orchestrate a Tree-of-Thought reasoning loop.
Generates 3 fix strategies, scores each, and selects the winning plan.

The plan drives every subsequent layer — it is the 'specification'
the code generation layer works from.

Technologies: LangGraph, GPT-4o API, Tree-of-Thought prompting, Pydantic
"""

import os
import json
from typing import Annotated, TypedDict, Optional
from dataclasses import dataclass

from pydantic import BaseModel, Field
from rich.console import Console

console = Console()


# ── Data Models ──────────────────────────────────────────────────────────────

class FixStrategy(BaseModel):
    """A single candidate fix strategy generated by Tree-of-Thought."""
    strategy_id: str = Field(description="A, B, or C")
    hypothesis: str = Field(description="Root cause hypothesis")
    approach: str = Field(description="How to fix it")
    affected_files: list[str] = Field(description="Files that need changes")
    affected_functions: list[str] = Field(description="Functions that need changes")
    risk_level: str = Field(description="low | medium | high")
    confidence_score: float = Field(description="0.0 to 1.0 confidence score")
    reasoning: str = Field(description="Why this strategy scores as it does")


class RepairPlan(BaseModel):
    """The complete structured plan output by Layer 2."""
    issue_summary: str = Field(description="One-line summary of the issue")
    root_cause: str = Field(description="Identified root cause")
    selected_strategy: FixStrategy = Field(description="The winning strategy")
    all_strategies: list[FixStrategy] = Field(description="All 3 generated strategies")
    target_files: list[str] = Field(description="Files to be modified")
    target_functions: list[str] = Field(description="Functions to be modified")
    expected_test_outcome: str = Field(description="What passing tests should look like after fix")
    risk_flags: list[str] = Field(description="Potential side effects or risks")


# ── LangGraph State ──────────────────────────────────────────────────────────

class PlanningState(TypedDict):
    """State passed between nodes in the LangGraph planning pipeline."""
    issue_text: str
    retrieved_chunks: list[dict]       # From Layer 1
    call_graph_context: str            # Relevant call graph subgraph
    strategies: list[FixStrategy]
    repair_plan: Optional[RepairPlan]
    error: Optional[str]
    memory_context: Optional[str]      # From Layer 7 (past similar issues)


# ── Prompts ──────────────────────────────────────────────────────────────────

TOT_GENERATION_PROMPT = """You are a senior software engineer analyzing a GitHub issue.

## GitHub Issue
{issue_text}

## Relevant Code Context (retrieved from codebase)
{code_context}

## Call Graph Context
{call_graph_context}

{memory_context}

## Your Task
Generate exactly 3 distinct fix strategies using Tree-of-Thought reasoning.
Each strategy must:
1. Propose a different root cause hypothesis
2. Target different code locations if possible
3. Have a different risk profile

For each strategy, provide a confidence score (0.0-1.0) based on:
- How well it explains the observed behavior
- Implementation feasibility  
- Risk of breaking other functionality

Return ONLY valid JSON matching this exact schema:
{{
  "strategies": [
    {{
      "strategy_id": "A",
      "hypothesis": "...",
      "approach": "...",
      "affected_files": ["file1.py"],
      "affected_functions": ["function_name"],
      "risk_level": "low|medium|high",
      "confidence_score": 0.84,
      "reasoning": "..."
    }},
    {{ "strategy_id": "B", ... }},
    {{ "strategy_id": "C", ... }}
  ]
}}"""


PLAN_SELECTION_PROMPT = """You are selecting the best fix strategy for a GitHub issue.

## Issue
{issue_text}

## Generated Strategies
{strategies_json}

## Selection Task
Choose the strategy with the highest confidence score.
Create the final RepairPlan. Return ONLY valid JSON:
{{
  "issue_summary": "...",
  "root_cause": "...",
  "selected_strategy": {{ ... (copy the winning strategy) }},
  "all_strategies": [ ... ],
  "target_files": ["file.py"],
  "target_functions": ["func_name"],
  "expected_test_outcome": "All existing tests pass plus edge case X is handled",
  "risk_flags": ["May affect callers of function X"]
}}"""


# ── LLM Client ───────────────────────────────────────────────────────────────

class LLMClient:
    """
    Unified LLM client that supports multiple providers.
    Start FREE with Groq, upgrade to OpenAI when ready.
    """

    def __init__(self):
        self.provider = os.getenv('LLM_PROVIDER', 'groq')
        self.model = os.getenv('LLM_MODEL', 'llama-3.1-70b-versatile')
        self._setup_client()

    def _setup_client(self):
        if self.provider == 'openai':
            from openai import OpenAI
            self.client = OpenAI(api_key=os.getenv('OPENAI_API_KEY'))
            console.print(f"[green]✓ LLM: OpenAI {self.model}[/green]")

        elif self.provider == 'groq':
            # Groq has a FREE tier — perfect for development!
            from groq import Groq
            self.client = Groq(api_key=os.getenv('GROQ_API_KEY'))
            console.print(f"[green]✓ LLM: Groq {self.model} (FREE tier)[/green]")

        elif self.provider == 'anthropic':
            import anthropic
            self.client = anthropic.Anthropic(api_key=os.getenv('ANTHROPIC_API_KEY'))
            console.print(f"[green]✓ LLM: Anthropic {self.model}[/green]")

        elif self.provider == 'ollama':
            # Completely FREE local models via Ollama
            console.print(f"[green]✓ LLM: Ollama (local, FREE)[/green]")
            self.client = None  # Uses requests directly

        else:
            raise ValueError(f"Unknown LLM provider: {self.provider}")

    def chat(self, system_prompt: str, user_prompt: str, temperature: float = 0.2) -> str:
        """Send a chat completion request."""
        if self.provider in ('openai', 'groq'):
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=temperature,
                response_format={"type": "json_object"},
            )
            return response.choices[0].message.content

        elif self.provider == 'ollama':
            import requests
            response = requests.post(
                'http://localhost:11434/api/chat',
                json={
                    "model": self.model,
                    "messages": [
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt}
                    ],
                    "stream": False,
                    "format": "json"
                }
            )
            return response.json()['message']['content']

        elif self.provider == 'anthropic':
            response = self.client.messages.create(
                model=self.model,
                max_tokens=4096,
                system=system_prompt,
                messages=[{"role": "user", "content": user_prompt}]
            )
            return response.content[0].text

        raise ValueError(f"Provider {self.provider} not implemented")


# ── Planning Agent ────────────────────────────────────────────────────────────

class PlanningAgent:
    """
    Layer 2: Autonomous Planning Agent using Tree-of-Thought.
    
    Usage:
        agent = PlanningAgent()
        plan = agent.create_plan(
            issue_text="...",
            retrieved_chunks=[...],
            call_graph_context="..."
        )
    """

    def __init__(self):
        self.llm = LLMClient()
        self._setup_langgraph()

    def _setup_langgraph(self):
        """Set up the LangGraph state machine."""
        try:
            from langgraph.graph import StateGraph, END
            
            workflow = StateGraph(PlanningState)
            workflow.add_node("generate_strategies", self._generate_strategies_node)
            workflow.add_node("select_plan", self._select_plan_node)
            workflow.add_node("handle_error", self._handle_error_node)
            
            workflow.set_entry_point("generate_strategies")
            workflow.add_conditional_edges(
                "generate_strategies",
                self._route_after_generation,
                {"select_plan": "select_plan", "handle_error": "handle_error"}
            )
            workflow.add_edge("select_plan", END)
            workflow.add_edge("handle_error", END)
            
            self.graph = workflow.compile()
            console.print("[green]✓ LangGraph planning workflow ready[/green]")
        except ImportError:
            console.print("[yellow]⚠ LangGraph not installed. Run: pip install langgraph[/yellow]")
            self.graph = None

    def create_plan(
        self,
        issue_text: str,
        retrieved_chunks: list[dict],
        call_graph_context: str = "",
        memory_context: str = ""
    ) -> Optional[RepairPlan]:
        """
        Main entry point: create a repair plan for a GitHub issue.
        
        Args:
            issue_text: The full GitHub issue text
            retrieved_chunks: Code chunks from Layer 1 retrieval
            call_graph_context: Relevant call graph subgraph text
            memory_context: Similar past issues from Layer 7
            
        Returns:
            RepairPlan with selected strategy and all metadata
        """
        console.print("\n[bold cyan]🧠 Planning Agent: Generating fix strategies...[/bold cyan]")

        initial_state: PlanningState = {
            "issue_text": issue_text,
            "retrieved_chunks": retrieved_chunks,
            "call_graph_context": call_graph_context,
            "strategies": [],
            "repair_plan": None,
            "error": None,
            "memory_context": memory_context
        }

        if self.graph:
            final_state = self.graph.invoke(initial_state)
        else:
            # Fallback: run nodes directly without LangGraph
            final_state = self._generate_strategies_node(initial_state)
            if not final_state.get('error'):
                final_state = self._select_plan_node(final_state)

        if final_state.get('error'):
            console.print(f"[red]✗ Planning failed: {final_state['error']}[/red]")
            return None

        plan = final_state.get('repair_plan')
        if plan:
            console.print(f"[bold green]✅ Plan ready: {plan.issue_summary}[/bold green]")
            console.print(f"   Strategy: {plan.selected_strategy.strategy_id} "
                         f"(confidence: {plan.selected_strategy.confidence_score:.2f})")
            console.print(f"   Target: {', '.join(plan.target_functions)}")

        return plan

    def _generate_strategies_node(self, state: PlanningState) -> PlanningState:
        """LangGraph node: generate 3 fix strategies."""
        # Format code context
        code_context = self._format_code_context(state['retrieved_chunks'])
        
        memory_section = ""
        if state.get('memory_context'):
            memory_section = f"\n## Past Similar Issues (from memory)\n{state['memory_context']}"

        prompt = TOT_GENERATION_PROMPT.format(
            issue_text=state['issue_text'],
            code_context=code_context,
            call_graph_context=state.get('call_graph_context', 'Not available'),
            memory_context=memory_section
        )

        try:
            response = self.llm.chat(
                system_prompt="You are an expert software engineer. Always respond with valid JSON only.",
                user_prompt=prompt
            )
            data = json.loads(response)
            strategies = [FixStrategy(**s) for s in data['strategies']]
            state['strategies'] = strategies
            console.print(f"[green]Generated {len(strategies)} strategies[/green]")
        except Exception as e:
            state['error'] = f"Strategy generation failed: {e}"

        return state

    def _select_plan_node(self, state: PlanningState) -> PlanningState:
        """LangGraph node: select best strategy and create repair plan."""
        strategies_json = json.dumps(
            [s.model_dump() for s in state['strategies']], indent=2
        )
        
        prompt = PLAN_SELECTION_PROMPT.format(
            issue_text=state['issue_text'],
            strategies_json=strategies_json
        )

        try:
            response = self.llm.chat(
                system_prompt="You are an expert software engineer. Always respond with valid JSON only.",
                user_prompt=prompt
            )
            data = json.loads(response)
            state['repair_plan'] = RepairPlan(**data)
        except Exception as e:
            state['error'] = f"Plan selection failed: {e}"

        return state

    def _handle_error_node(self, state: PlanningState) -> PlanningState:
        """LangGraph node: handle errors gracefully."""
        console.print(f"[red]Planning error: {state.get('error')}[/red]")
        return state

    def _route_after_generation(self, state: PlanningState) -> str:
        """LangGraph conditional edge: route based on success/failure."""
        return "handle_error" if state.get('error') else "select_plan"

    def _format_code_context(self, chunks: list[dict]) -> str:
        """Format retrieved code chunks for the prompt."""
        if not chunks:
            return "No code context retrieved."
        
        formatted = []
        for i, chunk in enumerate(chunks[:5]):  # Limit to top 5
            name = chunk.get('name', 'unknown')
            file_path = chunk.get('file_path', 'unknown')
            source = chunk.get('source_code', '')[:500]  # Limit source length
            formatted.append(f"### [{i+1}] {name} ({file_path})\n```python\n{source}\n```")
        
        return '\n\n'.join(formatted)


# ── Entry point for testing ────────────────────────────────────────────────

if __name__ == "__main__":
    from dotenv import load_dotenv
    load_dotenv('config/.env')

    agent = PlanningAgent()
    
    # Test with a sample issue
    test_issue = """
    Bug: calculate_discount() returns 0 when discount_rate is 0
    
    Expected: When discount_rate is 0, the function should return the original price.
    Actual: Returns 0 instead of the original price.
    
    Steps to reproduce:
    1. Call calculate_discount(price=100, discount_rate=0)
    2. Observe that it returns 0 instead of 100
    """
    
    test_chunks = [
        {
            "name": "calculate_discount",
            "file_path": "pricing/calculator.py",
            "source_code": """
def calculate_discount(price: float, discount_rate: float) -> float:
    if discount_rate:
        return price * discount_rate
    return 0
"""
        }
    ]
    
    plan = agent.create_plan(
        issue_text=test_issue,
        retrieved_chunks=test_chunks
    )
    
    if plan:
        console.print(f"\n[bold]Selected Strategy:[/bold] {plan.selected_strategy.strategy_id}")
        console.print(f"[bold]Root Cause:[/bold] {plan.root_cause}")
        console.print(f"[bold]Target:[/bold] {plan.target_functions}")
